export const HOUR = 3_600_000;
export const RESOURCES = ["gold", "wood", "stone", "aether"];
export const RESOURCE_NAMES = {
  gold: "Gold",
  wood: "Timber",
  stone: "Stone",
  aether: "Aether",
};
export const BUILDINGS = [
  {
    id: "keep",
    name: "The Keep",
    description:
      "The heart of your realm. Upgrade to unlock new buildings, stronger expeditions, and new chapters.",
    type: "keep",
    resource: null,
    base: 0,
    cost: { gold: 600, wood: 400, stone: 300 },
    time: 2,
    unlock: 1,
    max: 10,
  },
  {
    id: "lumber",
    name: "Lumber Mill",
    description:
      "Woodcutters turn the whispering forest into timber for your growing stronghold.",
    type: "lumber",
    resource: "wood",
    base: 36,
    cost: { gold: 220, wood: 100, stone: 90 },
    time: 1,
    unlock: 1,
    max: 10,
  },
  {
    id: "quarry",
    name: "Stone Quarry",
    description:
      "Stoneworkers uncover the foundations of a kingdom, one patient strike at a time.",
    type: "quarry",
    resource: "stone",
    base: 28,
    cost: { gold: 250, wood: 160, stone: 60 },
    time: 1,
    unlock: 1,
    max: 10,
  },
  {
    id: "mine",
    name: "Gold Mine",
    description:
      "Rich veins beneath the mountain fund your heroes and your next great ambition.",
    type: "mine",
    resource: "gold",
    base: 55,
    cost: { gold: 180, wood: 180, stone: 150 },
    time: 1,
    unlock: 1,
    max: 10,
  },
  {
    id: "spire",
    name: "Aether Spire",
    description:
      "Draw magic from the night sky. Aether calls new heroes through the summoning gate.",
    type: "spire",
    resource: "aether",
    base: 3,
    cost: { gold: 650, wood: 300, stone: 400 },
    time: 3,
    unlock: 2,
    max: 8,
  },
  {
    id: "guild",
    name: "Adventurers’ Guild",
    description:
      "Each level adds one simultaneous mission slot. A bigger guild means a wider world.",
    type: "guild",
    resource: null,
    base: 0,
    cost: { gold: 800, wood: 500, stone: 350 },
    time: 3,
    unlock: 2,
    max: 4,
  },
  {
    id: "warehouse",
    name: "Storehouse",
    description:
      "Each level adds 12 hours of offline storage, beyond the base 24-hour capacity.",
    type: "warehouse",
    resource: null,
    base: 0,
    cost: { gold: 700, wood: 650, stone: 250 },
    time: 2,
    unlock: 3,
    max: 4,
  },
  {
    id: "sanctum",
    name: "Moonwell Sanctum",
    description:
      "Each level adds 5 percentage points to mission success. Even heroes need a little luck.",
    type: "sanctum",
    resource: null,
    base: 0,
    cost: { gold: 1200, wood: 450, stone: 800 },
    time: 4,
    unlock: 3,
    max: 4,
  },
  {
    id: "academy",
    name: "Heroes’ Academy",
    description:
      "Each level increases expedition experience by 20%. Knowledge outlasts every battle.",
    type: "academy",
    resource: null,
    base: 0,
    cost: { gold: 1600, wood: 700, stone: 700 },
    time: 4,
    unlock: 4,
    max: 5,
  },
  {
    id: "observatory",
    name: "Star Observatory",
    description:
      "Each level increases all expedition resource rewards by 10%. Find fortune among the stars.",
    type: "observatory",
    resource: null,
    base: 0,
    cost: { gold: 2200, wood: 1000, stone: 1200 },
    time: 6,
    unlock: 5,
    max: 5,
  },
];
export const HEROES = [
  {
    id: "lyra",
    name: "Lyra Windwhisper",
    short: "Lyra",
    title: "Warden of the wild",
    role: "Ranger",
    affinity: "Grove",
    traits: ["Pathfinder", "Beast slayer"],
    rarity: "Rare",
    power: 88,
    art: "elf",
    color: "#5a8c73",
    skin: "#d7b69c",
  },
  {
    id: "aldric",
    name: "Aldric the Steadfast",
    short: "Aldric",
    title: "The unbroken shield",
    role: "Guardian",
    affinity: "Sun",
    traits: ["Defender", "Diplomat"],
    rarity: "Rare",
    power: 95,
    art: "knight",
    color: "#ad8a54",
    skin: "#d6b191",
  },
  {
    id: "mira",
    name: "Mira Ashborn",
    short: "Mira",
    title: "Keeper of the first flame",
    role: "Mage",
    affinity: "Ember",
    traits: ["Arcanist", "Undead slayer"],
    rarity: "Epic",
    power: 118,
    art: "mage",
    color: "#ad7068",
    skin: "#cc9f89",
  },
  {
    id: "bram",
    name: "Bram Ironroot",
    short: "Bram",
    title: "Friend of the mountain",
    role: "Warrior",
    affinity: "Stone",
    traits: ["Miner", "Defender"],
    rarity: "Common",
    power: 73,
    art: "dwarf",
    color: "#938471",
    skin: "#c18f70",
  },
  {
    id: "vesper",
    name: "Vesper Nightingale",
    short: "Vesper",
    title: "A whisper in the dark",
    role: "Rogue",
    affinity: "Moon",
    traits: ["Stealth", "Pathfinder"],
    rarity: "Rare",
    power: 90,
    art: "rogue",
    color: "#8582a6",
    skin: "#ba9ca3",
  },
  {
    id: "elowen",
    name: "Elowen Dawnlight",
    short: "Elowen",
    title: "Where hope takes root",
    role: "Healer",
    affinity: "Grove",
    traits: ["Healer", "Diplomat"],
    rarity: "Common",
    power: 72,
    art: "healer",
    color: "#7b9c87",
    skin: "#c69c78",
  },
  {
    id: "kael",
    name: "Kael Stormwarden",
    short: "Kael",
    title: "Thunder made flesh",
    role: "Warrior",
    affinity: "Storm",
    traits: ["Defender", "Beast slayer"],
    rarity: "Epic",
    power: 124,
    art: "knight",
    color: "#638f9c",
    skin: "#a17860",
  },
  {
    id: "seraphine",
    name: "Seraphine Solheart",
    short: "Seraphine",
    title: "The last sunkeeper",
    role: "Healer",
    affinity: "Sun",
    traits: ["Healer", "Arcanist"],
    rarity: "Legendary",
    power: 157,
    art: "healer",
    color: "#cfab65",
    skin: "#d8b8a0",
  },
  {
    id: "thorne",
    name: "Thorne Mossmantle",
    short: "Thorne",
    title: "Older than the forest",
    role: "Guardian",
    affinity: "Grove",
    traits: ["Defender", "Pathfinder"],
    rarity: "Epic",
    power: 122,
    art: "dwarf",
    color: "#657e56",
    skin: "#b58d65",
  },
  {
    id: "nyx",
    name: "Nyx Starweaver",
    short: "Nyx",
    title: "She who reads the void",
    role: "Mage",
    affinity: "Moon",
    traits: ["Arcanist", "Stealth"],
    rarity: "Legendary",
    power: 162,
    art: "mage",
    color: "#9c85ba",
    skin: "#baa3b9",
  },
  {
    id: "orin",
    name: "Orin Copperbeard",
    short: "Orin",
    title: "Fortune favors the bold",
    role: "Warrior",
    affinity: "Stone",
    traits: ["Miner", "Diplomat"],
    rarity: "Rare",
    power: 93,
    art: "dwarf",
    color: "#ba8552",
    skin: "#d0a07f",
  },
  {
    id: "sable",
    name: "Sable Swiftarrow",
    short: "Sable",
    title: "An arrow before dawn",
    role: "Ranger",
    affinity: "Moon",
    traits: ["Stealth", "Beast slayer"],
    rarity: "Epic",
    power: 119,
    art: "elf",
    color: "#75758f",
    skin: "#8f7266",
  },
  {
    id: "finn",
    name: "Finn Wayfarer",
    short: "Finn",
    title: "Every road is home",
    role: "Rogue",
    affinity: "Sun",
    traits: ["Pathfinder", "Diplomat"],
    rarity: "Common",
    power: 70,
    art: "rogue",
    color: "#a89869",
    skin: "#d2b08d",
  },
  {
    id: "astrid",
    name: "Astrid Frostveil",
    short: "Astrid",
    title: "The silence of winter",
    role: "Mage",
    affinity: "Storm",
    traits: ["Arcanist", "Undead slayer"],
    rarity: "Rare",
    power: 96,
    art: "mage",
    color: "#78a4b3",
    skin: "#d8bcb0",
  },
  {
    id: "durin",
    name: "Durin Ashhammer",
    short: "Durin",
    title: "Born beneath the mountain",
    role: "Guardian",
    affinity: "Ember",
    traits: ["Miner", "Defender"],
    rarity: "Epic",
    power: 127,
    art: "dwarf",
    color: "#a16753",
    skin: "#b68b70",
  },
  {
    id: "poppy",
    name: "Poppy Fernfoot",
    short: "Poppy",
    title: "Small steps, great journeys",
    role: "Healer",
    affinity: "Grove",
    traits: ["Healer", "Pathfinder"],
    rarity: "Common",
    power: 69,
    art: "healer",
    color: "#8b9b65",
    skin: "#ccab8d",
  },
  {
    id: "raven",
    name: "Raven Blacktide",
    short: "Raven",
    title: "Captain without a coast",
    role: "Rogue",
    affinity: "Storm",
    traits: ["Stealth", "Diplomat"],
    rarity: "Rare",
    power: 94,
    art: "rogue",
    color: "#637f8c",
    skin: "#b08b73",
  },
  {
    id: "sol",
    name: "Sol Emberwing",
    short: "Sol",
    title: "The phoenix remembers",
    role: "Warrior",
    affinity: "Ember",
    traits: ["Beast slayer", "Undead slayer"],
    rarity: "Legendary",
    power: 166,
    art: "knight",
    color: "#c48150",
    skin: "#b18061",
  },
  {
    id: "iris",
    name: "Iris Moonbrook",
    short: "Iris",
    title: "Still waters, deep magic",
    role: "Healer",
    affinity: "Moon",
    traits: ["Healer", "Arcanist"],
    rarity: "Rare",
    power: 87,
    art: "healer",
    color: "#8894b5",
    skin: "#d0b099",
  },
  {
    id: "cedric",
    name: "Cedric Goldleaf",
    short: "Cedric",
    title: "The honest blade",
    role: "Guardian",
    affinity: "Sun",
    traits: ["Defender", "Undead slayer"],
    rarity: "Common",
    power: 76,
    art: "knight",
    color: "#a29265",
    skin: "#ba8c70",
  },
  {
    id: "wren",
    name: "Wren Wildsong",
    short: "Wren",
    title: "Voice of the greenwood",
    role: "Ranger",
    affinity: "Grove",
    traits: ["Beast slayer", "Healer"],
    rarity: "Rare",
    power: 91,
    art: "elf",
    color: "#6f9273",
    skin: "#ad8062",
  },
  {
    id: "magnus",
    name: "Magnus Runeforge",
    short: "Magnus",
    title: "The living mountain",
    role: "Guardian",
    affinity: "Stone",
    traits: ["Miner", "Arcanist"],
    rarity: "Legendary",
    power: 160,
    art: "dwarf",
    color: "#999087",
    skin: "#c29979",
  },
  {
    id: "tala",
    name: "Tala Duskstep",
    short: "Tala",
    title: "Never where you look",
    role: "Rogue",
    affinity: "Ember",
    traits: ["Stealth", "Undead slayer"],
    rarity: "Common",
    power: 74,
    art: "rogue",
    color: "#a07d75",
    skin: "#a77b60",
  },
  {
    id: "zephyr",
    name: "Zephyr Skyborne",
    short: "Zephyr",
    title: "Follow the northern wind",
    role: "Ranger",
    affinity: "Storm",
    traits: ["Pathfinder", "Miner"],
    rarity: "Epic",
    power: 121,
    art: "elf",
    color: "#6c9f9a",
    skin: "#c9ac92",
  },
];
export const MISSIONS = [
  {
    id: "first",
    name: "A road worth taking",
    region: "THE OLD KING’S ROAD",
    text: "Our scouts found an abandoned supply wagon just beyond the gates. A perfect first expedition for your new company.",
    scene: "forest",
    hours: 1 / 12,
    power: 100,
    traits: ["Pathfinder", "Defender"],
    affinity: "Grove",
    slots: 2,
    rewards: { gold: 180, wood: 120, aether: 20 },
    xp: 45,
    tier: 1,
    intro: true,
  },
  {
    id: "whisper",
    name: "Whispers of the Wildwood",
    region: "THE EMERALD REACH",
    text: "Something stirs beneath the ancient canopy. Follow the tracks, protect the forest folk, and uncover what lies among the roots.",
    scene: "forest",
    hours: 4,
    power: 220,
    traits: ["Pathfinder", "Beast slayer"],
    affinity: "Grove",
    slots: 3,
    rewards: { gold: 380, wood: 260, aether: 15 },
    xp: 100,
    tier: 1,
  },
  {
    id: "mines",
    name: "Beneath the Hollow Peaks",
    region: "THE HOLLOW PEAKS",
    text: "The old mines are not as empty as we thought. Escort the prospectors through the mountain and bring its lost riches home.",
    scene: "mountain",
    hours: 6,
    power: 260,
    traits: ["Miner", "Defender"],
    affinity: "Stone",
    slots: 3,
    rewards: { gold: 500, stone: 350, aether: 20 },
    xp: 140,
    tier: 1,
  },
  {
    id: "lantern",
    name: "The lanterns of Dawnmere",
    region: "DAWNMERE VALLEY",
    text: "Carry medicine through the valley and negotiate safe passage for the winter caravans.",
    scene: "village",
    hours: 4,
    power: 210,
    traits: ["Healer", "Diplomat"],
    affinity: "Sun",
    slots: 3,
    rewards: { gold: 400, wood: 180, stone: 160 },
    xp: 100,
    tier: 1,
  },
  {
    id: "crypt",
    name: "An unquiet slumber",
    region: "THE FORGOTTEN HOLLOW",
    text: "Blue flames dance in the crypt. Break the binding spell before the forgotten rise again.",
    scene: "ruins",
    hours: 8,
    power: 360,
    traits: ["Undead slayer", "Arcanist"],
    affinity: "Moon",
    slots: 3,
    rewards: { gold: 650, stone: 400, aether: 40 },
    xp: 200,
    tier: 2,
  },
  {
    id: "ember",
    name: "Where embers sleep",
    region: "THE ASHEN FRONTIER",
    text: "A dragon’s abandoned nesting ground holds strange relics. Find a quiet route past its restless guardians.",
    scene: "volcano",
    hours: 8,
    power: 410,
    traits: ["Stealth", "Beast slayer"],
    affinity: "Ember",
    slots: 3,
    rewards: { gold: 700, wood: 350, aether: 45 },
    xp: 220,
    tier: 2,
  },
  {
    id: "storm",
    name: "Eye of the tempest",
    region: "THE STORM COAST",
    text: "An ancient lighthouse has gone dark. Brave the broken coast and rekindle the beacon that keeps the fleet alive.",
    scene: "mountain",
    hours: 12,
    power: 530,
    traits: ["Arcanist", "Defender"],
    affinity: "Storm",
    slots: 3,
    rewards: { gold: 1100, stone: 700, aether: 65 },
    xp: 320,
    tier: 3,
  },
  {
    id: "crown",
    name: "The sunken crown",
    region: "THE SILVER MARSH",
    text: "An old king’s crown waits beneath the marsh. Follow the star charts and avoid the sentinels that still keep watch.",
    scene: "ruins",
    hours: 12,
    power: 680,
    traits: ["Stealth", "Pathfinder"],
    affinity: "Moon",
    slots: 3,
    rewards: { gold: 1400, wood: 900, aether: 80 },
    xp: 400,
    tier: 4,
  },
  {
    id: "heart",
    name: "Heart of the first flame",
    region: "THE WORLD’S EDGE",
    text: "At the edge of every map, a flame still burns. Bring your finest company and discover why the stars went silent.",
    scene: "volcano",
    hours: 12,
    power: 880,
    traits: ["Arcanist", "Healer"],
    affinity: "Ember",
    slots: 3,
    rewards: { gold: 2100, stone: 1400, aether: 120 },
    xp: 550,
    tier: 5,
  },
];
export const DAILY_QUESTS = [
  {
    id: "collect",
    name: "A flourishing stronghold",
    text: "Collect resources from your buildings",
    target: 1,
    reward: { gold: 100, aether: 5 },
  },
  {
    id: "dispatch",
    name: "Adventure is calling",
    text: "Send heroes on 2 expeditions",
    target: 2,
    reward: { gold: 150, aether: 10 },
  },
  {
    id: "train",
    name: "A little stronger",
    text: "Train a hero once",
    target: 1,
    reward: { gold: 100, aether: 10 },
  },
];
export const LOGIN_REWARDS = [
  { gold: 250 },
  { wood: 300, stone: 200 },
  { aether: 40 },
  { gold: 500 },
  { wood: 500, stone: 400 },
  { aether: 60 },
  { aether: 120, gold: 750 },
];
export const CHAPTERS = [
  {
    name: "A spark in the wilderness",
    text: "Every great kingdom starts with a few brave souls and a place to call home.",
    keep: 1,
    missions: 1,
    heroes: 6,
    reward: { gold: 500, wood: 300, aether: 50 },
  },
  {
    name: "Roots run deep",
    text: "Raise your banners. Your little outpost is becoming something more.",
    keep: 2,
    missions: 4,
    heroes: 7,
    reward: { gold: 900, stone: 600, aether: 80 },
  },
  {
    name: "Beyond the familiar",
    text: "The roads are longer now, and the stories a little stranger.",
    keep: 3,
    missions: 10,
    heroes: 9,
    reward: { gold: 1500, wood: 1000, aether: 120 },
  },
  {
    name: "A gathering of legends",
    text: "Word of your company travels. Heroes answer from every corner of the realm.",
    keep: 4,
    missions: 20,
    heroes: 12,
    reward: { gold: 2500, stone: 1600, aether: 180 },
  },
  {
    name: "Written in the stars",
    text: "Build toward the heavens. There are still mysteries beyond the horizon.",
    keep: 5,
    missions: 35,
    heroes: 15,
    reward: { gold: 4000, wood: 2200, aether: 240 },
  },
  {
    name: "The long light",
    text: "The stronghold stands, a beacon for all who seek a better world.",
    keep: 7,
    missions: 60,
    heroes: 18,
    reward: { gold: 6500, stone: 3500, aether: 360 },
  },
  {
    name: "An ember, everlasting",
    text: "You did not conquer the world. You gave it somewhere to come home to.",
    keep: 10,
    missions: 100,
    heroes: 22,
    reward: { gold: 10000, wood: 5000, stone: 5000, aether: 600 },
  },
];
export const RARITY_COLORS = {
  Common: "#93a79e",
  Rare: "#79a9d1",
  Epic: "#b099dc",
  Legendary: "#e2b96d",
};
